apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfpecustomerapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Mfpecustomerapi
  template:
    metadata:
      labels:
        app: Mfpecustomerapi
    spec:
      containers:
      - name: mfpecustomerapirepos
        image: anujretailbankingcr.azurecr.io/mfpecustomerapirepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn2

---
apiVersion: v1
kind: Service
metadata:
  name: mfpecustomerapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Mfpecustomerapi
